#server port config
server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/weather?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&autoReconnect=true&useSSL=false&verifyServerCertificate=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10000
    virtual-host: /
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

# mybatis config
mybatis:
  type-aliases-package: com.demo.station.mapper
  mapper-locations: classpath*:mapper/*.xml

#log config
logging:
  level:
    root: info
  file:
    name: D:/weatherClient.log

# other common config
application:
  #rabbit exchange config
  rabbit:
    exchanger:
      name: weatherExchange
    queue:
      name: station1Queue




